using System.CodeDom.Compiler;
using System.Collections.Immutable;
using Kafka.Common.Protocol;
using ScramCredentialDeletion = Kafka.Client.Messages.AlterUserScramCredentialsRequest.ScramCredentialDeletion;
using ScramCredentialUpsertion = Kafka.Client.Messages.AlterUserScramCredentialsRequest.ScramCredentialUpsertion;

namespace Kafka.Client.Messages
{
    /// <summary>
    /// <param name="DeletionsField">The SCRAM credentials to remove.</param>
    /// <param name="UpsertionsField">The SCRAM credentials to update/insert.</param>
    /// </summary>
    [GeneratedCode("kgen", "1.0.0.0")]
    public sealed record AlterUserScramCredentialsRequest (
        ImmutableArray<ScramCredentialDeletion> DeletionsField,
        ImmutableArray<ScramCredentialUpsertion> UpsertionsField
    ) : Request(51)
    {
        public static AlterUserScramCredentialsRequest Empty { get; } = new(
            ImmutableArray<ScramCredentialDeletion>.Empty,
            ImmutableArray<ScramCredentialUpsertion>.Empty
        );
        /// <summary>
        /// <param name="NameField">The user name.</param>
        /// <param name="MechanismField">The SCRAM mechanism.</param>
        /// </summary>
        public sealed record ScramCredentialDeletion (
            string NameField,
            sbyte MechanismField
        )
        {
            public static ScramCredentialDeletion Empty { get; } = new(
                "",
                default(sbyte)
            );
        };
        /// <summary>
        /// <param name="NameField">The user name.</param>
        /// <param name="MechanismField">The SCRAM mechanism.</param>
        /// <param name="IterationsField">The number of iterations.</param>
        /// <param name="SaltField">A random salt generated by the client.</param>
        /// <param name="SaltedPasswordField">The salted password.</param>
        /// </summary>
        public sealed record ScramCredentialUpsertion (
            string NameField,
            sbyte MechanismField,
            int IterationsField,
            ImmutableArray<byte> SaltField,
            ImmutableArray<byte> SaltedPasswordField
        )
        {
            public static ScramCredentialUpsertion Empty { get; } = new(
                "",
                default(sbyte),
                default(int),
                ImmutableArray<byte>.Empty,
                ImmutableArray<byte>.Empty
            );
        };
    };
}